version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:latest
  working_directory: ~/repo

jobs:
  python-scripts:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-py-cache-{{ .Branch }}-{{ checksum "scripts/requirements.txt" }}
      - run:
          name: Activate venv and install requirements
          command: |
            python3 -m venv venv
            source venv/bin/activate
            cd scripts
            pip3 install -r requirements.txt
      - run:
          name: Check for empty schema sections
          command: |
            cd scripts
            python3 empty_sections.py ../schema
      - run:
          name: Check for responsible person section
          command: |
            cd scripts
            python3 responsible_person.py ../schema

workflows:
  version: 2
  build:
    jobs:
      - python-scripts
