version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get install libxml2-utils
      - run:
          name: Find empty displayterm text
          command: grep -rnE schema -e '<dtyp:displayterm value=".*?" *?><' && exit 1
