version: 2
jobs:
  python:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install libxml2-utils
      - run:
          name: Find empty CBECCresXMLterm text
          command: grep -rnE schema -e '<dtyp:CBECCresXMLterm value=".*?" *?><'
      - run:
          name: Validate schema files
          command: |
            cd tools
            sh ./validate-schema.sh || exit 1
      - run:
          name: Find empty displayterm text
          command: grep -rnE schema -e '<dtyp:displayterm value=".*?" *?><' && exit 1
      - run:
          name: Validate deployed schema files
          command: |
            cd tools
            sh ./validate-deployed-schema.sh || exit 1

workflows:
  version: 2
  build:
    jobs:
      - python


