version: 2.1

orbs:
  python: circleci/python@0.2.1
  ruby: circleci/ruby@0.2.1

jobs:
  python-scripts:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Checking schema well-formedness
          command: |
            cd scripts
            python3 lint_schema.py
      - run:
          name: Checking empty schema sections
          command: |
            cd scripts
            python3 empty_sections.py
          when: always
      - run:
          name: Checking responsible person sections
          command: |
            cd scripts
            python3 responsible_person.py
          when: always
      - run:
          name: Checking d:list inside d:list
          command: |
            cd scripts
            python3 d_list_markup.py
          when: always
      - run:
          name: Checking missing schema sections
          command: |
            cd scripts
            python3 missing_sections.py
          when: always
      - run:
          name: Checking for mismatched ComplianceDocument tags
          command: |
            cd scripts
            python3 compliance_document.py
          when: always
      - run:
          name: Checking for mismatched Header
          command: |
            cd scripts
            python3 header.py
          when: always
      - run:
          name: Checking for duplicate elements in each schema section
          command: |
            cd scripts
            python3 duplicate_elements.py
          when: always
      - run:
          name: Checking for incorrect end note naming in each schema section
          command: |
            cd scripts
            python3 end_notes.py
          when: always
      - run:
          name: Checking for empty displayterm tags
          command: |
            cd scripts
            python3 empty_displayterm.py
          when: always
      - run:
          name: Checking for missing base elements
          command: |
            cd scripts
            python3 missing_base_elements.py
          when: always
      - run:
          name: Checking for missing namespace declarations
          command: |
            cd scripts
            python3 namespace_prefixes.py
      - run:
          name: Checking for a mismatch between targetNamespace
          command: |
            cd scripts
            python3 document_mismatch.py

  oxygen-xml:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run:
          name: Download and install Oxygen XML
          command: |
            wget https://mirror.oxygenxml.com/InstData/Editor/Linux64/VM/oxygen-64bit-openjdk.sh
            sh oxygen-64bit-openjdk.sh -q -overwrite -console

workflows:
  version: 2
  build:
    jobs:
      - python-scripts
